package com.hwangrq.dianping.dal;

import com.hwangrq.dianping.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    UserModel selectByPrimaryKey(Integer id);

    UserModel selectByTelephoneAndPassword(@Param("telephone") String telephone,
                                           @Param("password") String password);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Sat Aug 14 01:17:45 GMT+08:00 2021
     */
    int updateByPrimaryKey(UserModel record);

    Integer countAllUser();
}